// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VostokExchRateWebAPI.Data;

#nullable disable

namespace VostokExchRateWebAPI.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20241020151300_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("VostokExchRateWebAPI.Models.CurrencyModel", b =>
                {
                    b.Property<short>("Code")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("INTEGER");

                    b.Property<float>("Buy")
                        .HasMaxLength(10)
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<float>("Sell")
                        .HasMaxLength(10)
                        .HasColumnType("REAL");

                    b.Property<string>("ShortName")
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.ToTable("Currencies");
                });
#pragma warning restore 612, 618
        }
    }
}
